### ISSUE TITLE
Function doesFileExist doesn't use path in parameter

### ISSUE THREAD

**Issue by Carlos85G** [bttfhillvalley/vc-cleo-plugins#1]
Function doesFileExists always looks for file ".\\DATA\\HANDLING_ADDITIONAL.CFG" instead of the passed string.

https://github.com/bttfhillvalley/vc-cleo-plugins/blob/174f616a7292435c16fdc292b29e09eac536e210/bttfhv/bttfhv/bttfhv.cpp#L2048C53-L2048C53

**Comment by KyonkoYuuki** [comment]
Fixed
