### ISSUE TITLE
char m_nHandlingFlags overwritten with int?

### ISSUE THREAD

**Issue by Carlos85G** [bttfhillvalley/vc-cleo-plugins#2]
https://github.com/bttfhillvalley/vc-cleo-plugins/blob/174f616a7292435c16fdc292b29e09eac536e210/bttfhv/bttfhv/bttfhv.cpp#L2233C7-L2233C72

Can this cause the handling flags to be scrambled in-game? For the DeLorean, this seems to write 0x4308087 (70287495) into the `m_nHandlingFlags` property, which is a `char`, not `int`. Wouldn't the property expect the raw value in hex  "4308087" (as string)?

**Comment by KyonkoYuuki** [comment]
This is what the game does already apparently.
