### ISSUE TITLE
Lite - Modloader: Unable to ignore mod

### ISSUE THREAD

**Issue by Carlos85G** [bttfhillvalley/vc-cleo-plugins#3]
If the directory `.\modloader\bttf hv_lite` is missing, or if the mod itself is ignored in `.\modloader\modloader.ini` the game will crash.

Is it possible for the plugin to only work when the mod is enabled?

![image](https://github.com/bttfhillvalley/vc-cleo-plugins/assets/23388293/30cf054c-ebe7-4321-9307-dd19cd9ceca3)

**Comment by KyonkoYuuki** [comment]
handling_additional.cfg and carcols_additional.cfg are not part of modloader and are in the base data directory.  By disabling the mod, you now have two files that references models that would have been defined in default.ide that are no longer there thus it crashes.
